payment points details
MobilePayDev/MobilePay-Payments-API pull request #20
Opened 2021-11-03 09:57 UTC by jmiliMP

Added example for retrieving payment points and updated redirect to github docs on clicking logo.

2021-11-03 10:08 UTC, granatoidas approved these changes

2021-11-03 10:44 UTC, edvinasmuncelis requested changes

2021-11-03 10:44 UTC, edvinasmuncelis commented on docs/payment-points-api.md
> +In order to get the details of payment points like `PaymentPointId`, you need to call Payment Points Api. The following request retrieves information about all the payment points for a merchant accou
API should be all uppercase letters since it's an acronym.

2021-11-03 10:44 UTC, edvinasmuncelis commented on docs/payment-points-api.md
> +In order to get the details of payment points like `PaymentPointId`, you need to call Payment Points Api. The following request retrieves information about all the payment points for a merchant accou
"_you need to use Payment Points API_"

2021-11-03 10:44 UTC, edvinasmuncelis commented on docs/payment-points-api.md
> +In order to get the details of payment points like `PaymentPointId`, you need to call Payment Points Api. The following request retrieves information about all the payment points for a merchant accou
remove "the"

2021-11-03 10:44 UTC, edvinasmuncelis commented on docs/payment-points-api.md
> +In order to get the details of payment points like `PaymentPointId`, you need to call Payment Points Api. The following request retrieves information about all the payment points for a merchant accou
replace "product" with "API"

2021-11-04 07:22 UTC, edvinasmuncelis approved these changes

2021-11-04 07:24 UTC, merged