Update query parameter format from date-time to date
MobilePayDev/MobilePay-Payments-API pull request #66
Opened 2022-08-26 21:33 UTC by bilfeldt

The query parameters were incorrectly marked as format `date-time` while the only accepted format was in fact a simple `date`

2022-09-01 13:21 UTC, edvinasmuncelis commented
Hello @bilfeldt . Thanks for reaching out. We double checked this and date-time is accepted normally. Could you please send us a `correlationId` of the request which failed for you?

2022-09-01 13:46 UTC, bilfeldt commented
@edvinasmuncelis sure thing:

- URL: `https://api.mobilepay.dk/v3/reporting/transfers?startdate=2022-08-31T13%3A44%3A30Z&pagenumber=1&pagesize=1000`
- correlationId: `c3d619c7-f28d-4289-b4a3-96541150d0bc`
- message: `startdate:Invalid input`

Let me know if I am missing something here? Thanks.

2022-09-01 14:05 UTC, edvinasmuncelis requested changes
@bilfeldt You are right 👍  I missed that transfers do actually accept only date.
You've also edited `transactions`, which actually use date-time. Could you please revert that?

2022-09-01 14:05 UTC, edvinasmuncelis commented on openapi/reporting.yaml
> +            format: date
this is actually date-time

2022-09-01 14:05 UTC, edvinasmuncelis commented on openapi/reporting.yaml
> +            format: date
this should be date-time as well

2022-09-01 14:10 UTC, bilfeldt commented on openapi/reporting.yaml
> +            format: date
Reverted

2022-09-01 14:11 UTC, bilfeldt commented
@edvinasmuncelis hereby reverted.

Is there any sorting parameters for any of the endpoints that are not documented? The `transfers` sort in reverse order of the `transactions` endpoint per default I can see.

2022-09-01 14:16 UTC, edvinasmuncelis approved these changes
@bilfeldt Thank you for contributing!

2022-09-01 14:17 UTC, merged

2022-09-02 06:30 UTC, edvinasmuncelis commented
> The `transfers` sort in reverse order of the `transactions` endpoint per default I can see.

No, we've documented all parameters, that are implemented. Regarding sorting of transfers, we'll take a look at it.